basePath: /
definitions:
  http.signInResponse:
    properties:
      token:
        type: string
    type: object
  http.signRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
host: localhost:8085
info:
  contact: {}
  description: 'This is a simple crm system by two extraordinary guys: Musamir & Azino'
  title: CRM System by Musamir & Azino
  version: "1.0"
paths:
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: signIn checks the users login and password and returns token if
        the user exists
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/http.signRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.signInResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: signIn
      tags:
      - auth
  /safe/business/test:
    get:
      description: test is used to test your jwt token. It return "hello" if your
        token is suitable
      produces:
      - application/json
      responses:
        "200":
          description: hello
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
        "401":
          description: Unauthorized!!
          schema:
            type: string
        "500":
          description: something went wrong
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: test
      tags:
      - safe
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
